from client import post, get
from session import get_uid


async def store_capsule(
    topic_id: str,
    content_md: str,
    summary: str,
    review_questions: list[dict],
    user_id: str = "",
) -> dict:
    """Store a capsule generated by the agent. Returns {capsule_id}.

    review_questions: list of {question, correct_answer, difficulty}
    """
    return await post("/api/capsules", {
        "user_id": await get_uid(user_id),
        "topic_id": topic_id,
        "content_md": content_md,
        "summary": summary,
        "review_questions": review_questions,
    })


async def get_capsule(capsule_id: str) -> dict:
    """Fetch a stored capsule with its review questions."""
    return await get(f"/api/capsules/{capsule_id}")
